name: mic_app
description: MIC Framework - Neural Mobile Engine

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  record: ^5.0.0
  tflite_flutter: ^0.10.4
  flutter_isolate: ^2.0.4
  permission_handler: ^11.0.0
  riverpod: ^2.5.0
  flutter_riverpod: ^2.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/model_image.tflite
    - assets/model_audio.tflite
    - assets/labels_image.txt
    - assets/labels_audio.txt
